version: '3.5'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - '4000:4000'  # Expose the port defined by your application (4000 in this case)
